env:
  _target_: envs.reacher.sim.CarEnv
  real_time: false

env_real:
  _target_: envs.reacher.real.RealEnv
  address: ${oc.env:ROBOT_MAC_ADDRESS}

model:
  _target_: stable_baselines3.PPO
  policy: MlpPolicy
  verbose: true
  env: ${env}

training_parameters:
  _target_: train.TrainingParameters
  save_prefix: ppo_car_reacher
  total_timesteps: 1e5
