env:
  _target_: rl_car.envs.gripper_one_object.sim.CarEnv
  real_time: false

env_real:
  _target_: rl_car.envs.gripper_one_object.real.RealEnv
  address: ${oc.env:ROBOT_MAC_ADDRESS}

model:
  _target_: stable_baselines3.SAC
  policy: MlpPolicy
  verbose: true
  env: ${env}

training_parameters:
  _target_: train.TrainingParameters
  save_prefix: ppo_car_gripper
  total_timesteps: 1e6
